version: 2.1
#version: 2

jobs:
  build:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout
      - run:
          name: Python-TK and Python-SIM install (VM Bug)
          command: |
            apt-get install -y sudo
            sudo apt-get update
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - #Chrome linux keys error fix
            sudo apt-get update
            sudo apt-get install sip-dev
            sudo apt-get install tk-dev
            pyenv install -f 2.7.12
            
      - run:
          name: Installer Python2
          command: |
            pip install --upgrade pip
            cd ~/project/robots/LoCoBot/install
            chmod +x locobot_install_all.sh
            ./locobot_install_all.sh -t sim_only -p 2
 
      - run:
          name: Installer Python3
          command: |
            source ~/.bashrc
            cd ~/project
            chmod +x install_pyrobot.sh
            ./install_pyrobot.sh -p 3
            cd ~/project/robots/LoCoBot
            source ~/pyenv_pyrobot_python3/bin/activate
            pip3 install --ignore-installed -r requirements_python3.txt
            deactivate
     
      - run:
          name: Gazebo 7 VM bug fix
          command: |
            sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
            wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install gazebo7 -y
            
      - run:
          name: Fake Display
          command: |
            Xvfb :1 -screen 0 1600x1200x16  &
            export DISPLAY=:1.0
      - run:
          name: Sip 4.17 VM Bug fix
          command: |
            cd ~/
            source ~/pyenv_pyrobot_python2/bin/activate
            wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.zip
            unzip sip-4.17.zip
            cd sip-4.17/
            python configure.py --incdir=~/pyenv_pyrobot_python2/include/python2.7
            make
            make install
            cd ..
            pip install lxml
            deactivate
      
      #- run:
      #    name: Python2 Tests
      #    command: |
      #      source ~/.bashrc
      #      source ~/pyenv_pyrobot_python2/bin/activate
      #      cd ~/low_cost_ws/src/pyrobot/tests
      #      python run_test.py --out_dir htmlcov/`git rev-parse HEAD` --nobrowser
      
      - run:
          name: Run Gazebo in the background
          command: |
            source ~/.bashrc
            source ~/pyenv_pyrobot_python2/bin/activate
            roslaunch locobot_control main.launch use_sim:=true
          no_output_timeout: 1.00h
          background: true
      
      - run:
          name: Run tests
          command: |
            sleep 150 # Wait for Gazebo to properly spin up
            source ~/.bashrc
            cd ~/project/tests/
            chmod +x circleci_tests.sh
            ./circleci_tests.sh
       
