version: 2.1
#version: 2

jobs:
  build:
    resource_class: xlarge
    docker:
      - image: ros:melodic-robot-bionic

    steps:
      - checkout
      - run:
          name: Python-TK and Python-SIM install (VM Bug)
          command: |
            apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
            #wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - #Chrome linux keys error fix
            sudo apt-get update -y
            sudo apt-get install -y python-setuptools python-pip
            #pyenv install -f 2.7.12
            
            export DEBIAN_FRONTEND=noninteractive

            ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
            sudo apt-get install -y tzdata
            dpkg-reconfigure --frontend noninteractive tzdata
            
            apt-get update && apt-get install -y lsb-release && apt-get clean all
            
            #sudo apt-get install -y sip-dev
            #sudo apt-get install -y tk-dev
            
      - run:
          name: Installer Python2
          command: |
            sudo apt-get install -y python-rosdep
            cd ~/project/robots/LoCoBot/install
            chmod +x locobot_install_all.sh
            ./locobot_install_all.sh -t sim_only -p 2
 
      - run:
          name: Installer Python3
          command: |
            source ~/.bashrc
            cd ~/project
            chmod +x install_pyrobot.sh
            ./install_pyrobot.sh -p 3
            cd ~/project/robots/LoCoBot
            source ~/pyenv_pyrobot_python3/bin/activate
            pip3 install --ignore-installed -r requirements_python3.txt
            deactivate
                 
      - run:
          name: Fake Display
          command: |
            Xvfb :1 -screen 0 1600x1200x16  &
            export DISPLAY=:1.0      
      #- run:
      #    name: Python2 Tests
      #    command: |
      #      source ~/.bashrc
      #      source ~/pyenv_pyrobot_python2/bin/activate
      #      cd ~/low_cost_ws/src/pyrobot/tests
      #      python run_test.py --out_dir htmlcov/`git rev-parse HEAD` --nobrowser
      
      - run:
          name: Run Gazebo in the background
          command: |
            source ~/.bashrc
            source ~/pyenv_pyrobot_python2/bin/activate
            roslaunch locobot_control main.launch use_sim:=true
          no_output_timeout: 1.00h
          background: true
      
      - run:
          name: Run tests
          command: |
            sleep 150 # Wait for Gazebo to properly spin up
            source ~/.bashrc
            cd ~/project/tests/
            chmod +x circleci_tests.sh
            ./circleci_tests.sh
       
